#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Sep 15, 2020 04:29:01 PM CST  platform: Windows NT

import sys
import hashlib




def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top



def Text1():        #获得输入的值
    count = 0



def Text2():      #显示计算的md5值
    print()



def button1():        #计算md5值

    print()


def button2():        #清空Text1框中的值
    print()





if __name__ == '__main__':
    import unknown
    unknown.vp_start_gui()




